export type Book = {
  id: string
  name: string
  testament: 'Old Testament' | 'New Testament'
  order: number
  chapters: number
  writer: string
  verse: string
  cite: string
  about: string
}

export const books: Book[] = [
  { id: 'gen', name: 'Genesis', testament: 'Old Testament', order: 1, chapters: 50, writer: 'Moses', cite: '1:1', verse: 'In the beginning God created the heaven and the earth.', about: 'Beginnings: the world, a family, and a promise that will not let go of Abraham’s line.' },
  { id: 'exo', name: 'Exodus', testament: 'Old Testament', order: 2, chapters: 40, writer: 'Moses', cite: '3:14', verse: 'And God said unto Moses, I AM THAT I AM.', about: 'Israel leaves Egypt. A name is spoken from a bush, and a people is pulled through the sea.' },
  { id: 'lev', name: 'Leviticus', testament: 'Old Testament', order: 3, chapters: 27, writer: 'Moses', cite: '19:2', verse: 'Ye shall be holy: for I the Lord your God am holy.', about: 'How a holy God lives among an ordinary camp — offerings, days, and the weight of nearness.' },
  { id: 'num', name: 'Numbers', testament: 'Old Testament', order: 4, chapters: 36, writer: 'Moses', cite: '6:24', verse: 'The Lord bless thee, and keep thee.', about: 'Census and wilderness. A generation walks in circles until the promise is ready for the next.' },
  { id: 'deu', name: 'Deuteronomy', testament: 'Old Testament', order: 5, chapters: 34, writer: 'Moses', cite: '6:4', verse: 'Hear, O Israel: The Lord our God is one Lord.', about: 'Moses’ last sermon on the plain. Remember, love, and teach the words when you reach the land.' },
  { id: 'jos', name: 'Joshua', testament: 'Old Testament', order: 6, chapters: 24, writer: 'Joshua', cite: '24:15', verse: 'As for me and my house, we will serve the Lord.', about: 'The Jordan parts. Cities fall. A people must decide whom they will serve in the new land.' },
  { id: 'jdg', name: 'Judges', testament: 'Old Testament', order: 7, chapters: 21, writer: 'Samuel', cite: '21:25', verse: 'Every man did that which was right in his own eyes.', about: 'Cycles of forgetting. Deliverers rise, then the land slips again when there is no king.' },
  { id: 'rut', name: 'Ruth', testament: 'Old Testament', order: 8, chapters: 4, writer: 'Samuel', cite: '1:16', verse: 'Whither thou goest, I will go.', about: 'A Moabite widow gleans in Bethlehem and is folded into Israel’s hope — and David’s line.' },
  { id: '1sa', name: '1 Samuel', testament: 'Old Testament', order: 9, chapters: 31, writer: 'Samuel', cite: '16:7', verse: 'Man looketh on the outward appearance, but the Lord looketh on the heart.', about: 'From Hannah’s prayer to a tall king, then a shepherd. The throne is not what it seems.' },
  { id: '2sa', name: '2 Samuel', testament: 'Old Testament', order: 10, chapters: 24, writer: 'Samuel / Nathan', cite: '7:16', verse: 'Thine house and thy kingdom shall be established for ever.', about: 'David’s rise and the crack in the house. A covenant stands even when the king falls.' },
  { id: '1ki', name: '1 Kings', testament: 'Old Testament', order: 11, chapters: 22, writer: 'Jeremiah', cite: '8:27', verse: 'Will God indeed dwell on the earth?', about: 'Solomon’s temple, then the split. Prophets stand in courts that will not listen.' },
  { id: '2ki', name: '2 Kings', testament: 'Old Testament', order: 12, chapters: 25, writer: 'Jeremiah', cite: '2:11', verse: 'The chariot of Israel, and the horsemen thereof.', about: 'Israel and Judah run out of time. Elijah is taken; Jerusalem is taken; the line is not.' },
  { id: '1ch', name: '1 Chronicles', testament: 'Old Testament', order: 13, chapters: 29, writer: 'Ezra', cite: '16:34', verse: 'For his mercy endureth for ever.', about: 'Genealogies and David again, told for those coming home who need to know who they are.' },
  { id: '2ch', name: '2 Chronicles', testament: 'Old Testament', order: 14, chapters: 36, writer: 'Ezra', cite: '7:14', verse: 'If my people, which are called by my name, shall humble themselves…', about: 'Kings measured by the temple. Reform, ruin, and a decree that lets the remnant return.' },
  { id: 'ezr', name: 'Ezra', testament: 'Old Testament', order: 15, chapters: 10, writer: 'Ezra', cite: '7:10', verse: 'For Ezra had prepared his heart to seek the law of the Lord.', about: 'The return from exile. The house is rebuilt, and the book is opened in the square.' },
  { id: 'neh', name: 'Nehemiah', testament: 'Old Testament', order: 16, chapters: 13, writer: 'Nehemiah', cite: '8:10', verse: 'The joy of the Lord is your strength.', about: 'Walls in fifty-two days, and a people who weep when the law is read aloud.' },
  { id: 'est', name: 'Esther', testament: 'Old Testament', order: 17, chapters: 10, writer: 'Unknown', cite: '4:14', verse: 'Who knoweth whether thou art come to the kingdom for such a time as this?', about: 'A hidden name, a public risk. A feast is kept because a queen would not stay silent.' },
  { id: 'job', name: 'Job', testament: 'Old Testament', order: 18, chapters: 42, writer: 'Unknown', cite: '19:25', verse: 'I know that my redeemer liveth.', about: 'A blameless man sits in ashes and asks why. Friends talk. Then the whirlwind answers.' },
  { id: 'psa', name: 'Psalms', testament: 'Old Testament', order: 19, chapters: 150, writer: 'David and others', cite: '23:1', verse: 'The Lord is my shepherd; I shall not want.', about: 'The hymnbook of Israel — complaint, thanks, and a king who still has to ask for mercy.' },
  { id: 'pro', name: 'Proverbs', testament: 'Old Testament', order: 20, chapters: 31, writer: 'Solomon and others', cite: '1:7', verse: 'The fear of the Lord is the beginning of knowledge.', about: 'Wisdom in the gate and at the table. Short lines that teach a long life.' },
  { id: 'ecc', name: 'Ecclesiastes', testament: 'Old Testament', order: 21, chapters: 12, writer: 'Qoheleth', cite: '12:13', verse: 'Fear God, and keep his commandments: for this is the whole duty of man.', about: 'Under the sun everything turns. The preacher still ends with fear and the work of the hands.' },
  { id: 'sng', name: 'Song of Songs', testament: 'Old Testament', order: 22, chapters: 8, writer: 'Solomon', cite: '2:4', verse: 'His banner over me was love.', about: 'A love song that will not be hurried. Desire, garden, and a seal on the heart.' },
  { id: 'isa', name: 'Isaiah', testament: 'Old Testament', order: 23, chapters: 66, writer: 'Isaiah', cite: '9:6', verse: 'For unto us a child is born, unto us a son is given.', about: 'Holy, holy, holy — then comfort. A servant, a child, and a city that will be new.' },
  { id: 'jer', name: 'Jeremiah', testament: 'Old Testament', order: 24, chapters: 52, writer: 'Jeremiah', cite: '29:11', verse: 'For I know the thoughts that I think toward you, saith the Lord.', about: 'The weeping prophet. A city will fall, and still a new covenant is promised in the wreckage.' },
  { id: 'lam', name: 'Lamentations', testament: 'Old Testament', order: 25, chapters: 5, writer: 'Jeremiah', cite: '3:22', verse: 'It is of the Lord’s mercies that we are not consumed.', about: 'Acrostic grief over Jerusalem. Mercies are new in the morning even when the walls are not.' },
  { id: 'eze', name: 'Ezekiel', testament: 'Old Testament', order: 26, chapters: 48, writer: 'Ezekiel', cite: '36:26', verse: 'A new heart also will I give you.', about: 'Visions by the river Chebar. Dry bones, a new heart, and a temple measured for hope.' },
  { id: 'dan', name: 'Daniel', testament: 'Old Testament', order: 27, chapters: 12, writer: 'Daniel', cite: '2:44', verse: 'The God of heaven [shall] set up a kingdom, which shall never be destroyed.', about: 'Exile in a palace. Furnaces, lions, and nights that belong to another kingdom.' },
  { id: 'hos', name: 'Hosea', testament: 'Old Testament', order: 28, chapters: 14, writer: 'Hosea', cite: '6:6', verse: 'I desired mercy, and not sacrifice.', about: 'A prophet’s marriage becomes the sermon. Love that will not file the papers.' },
  { id: 'joe', name: 'Joel', testament: 'Old Testament', order: 29, chapters: 3, writer: 'Joel', cite: '2:28', verse: 'I will pour out my spirit upon all flesh.', about: 'Locusts first. Then the spirit on sons and daughters, and a valley of decision.' },
  { id: 'amo', name: 'Amos', testament: 'Old Testament', order: 30, chapters: 9, writer: 'Amos', cite: '5:24', verse: 'Let judgment run down as waters, and righteousness as a mighty stream.', about: 'A herdsman at Bethel. Luxury is weighed, and the poor are not forgotten.' },
  { id: 'oba', name: 'Obadiah', testament: 'Old Testament', order: 31, chapters: 1, writer: 'Obadiah', cite: '1:4', verse: 'Though thou exalt thyself as the eagle… thence will I bring thee down.', about: 'One chapter for Edom. Pride on the cliff does not keep the house.' },
  { id: 'jon', name: 'Jonah', testament: 'Old Testament', order: 32, chapters: 4, writer: 'Jonah', cite: '2:9', verse: 'Salvation is of the Lord.', about: 'A prophet runs the other way. A fish, a city, and a lesson about mercy he did not want.' },
  { id: 'mic', name: 'Micah', testament: 'Old Testament', order: 33, chapters: 7, writer: 'Micah', cite: '6:8', verse: 'To do justly, and to love mercy, and to walk humbly with thy God.', about: 'From Bethlehem a ruler. What the Lord requires is smaller and harder than a thousand rams.' },
  { id: 'nah', name: 'Nahum', testament: 'Old Testament', order: 34, chapters: 3, writer: 'Nahum', cite: '1:7', verse: 'The Lord is good, a strong hold in the day of trouble.', about: 'Nineveh’s end. Comfort for those who waited under an empire.' },
  { id: 'hab', name: 'Habakkuk', testament: 'Old Testament', order: 35, chapters: 3, writer: 'Habakkuk', cite: '2:4', verse: 'The just shall live by his faith.', about: 'A prophet argues with God about justice, then stands watch and sings anyway.' },
  { id: 'zep', name: 'Zephaniah', testament: 'Old Testament', order: 36, chapters: 3, writer: 'Zephaniah', cite: '3:17', verse: 'The Lord thy God in the midst of thee is mighty; he will save.', about: 'The day of the Lord is near — and still he will quiet his people with love.' },
  { id: 'hag', name: 'Haggai', testament: 'Old Testament', order: 37, chapters: 2, writer: 'Haggai', cite: '2:9', verse: 'The glory of this latter house shall be greater than of the former.', about: 'Rebuild the house. Paneled rooms can wait; the Lord’s house cannot.' },
  { id: 'zec', name: 'Zechariah', testament: 'Old Testament', order: 38, chapters: 14, writer: 'Zechariah', cite: '9:9', verse: 'Behold, thy King cometh unto thee… lowly, and riding upon an ass.', about: 'Night visions and a lowly king. The branch, the fountain, and a city without walls of fear.' },
  { id: 'mal', name: 'Malachi', testament: 'Old Testament', order: 39, chapters: 4, writer: 'Malachi', cite: '4:2', verse: 'Unto you that fear my name shall the Sun of righteousness arise.', about: 'The last word before the long quiet. A messenger, a refining fire, and hearts turned home.' },
  { id: 'mat', name: 'Matthew', testament: 'New Testament', order: 40, chapters: 28, writer: 'Matthew', cite: '5:14', verse: 'Ye are the light of the world. A city that is set on an hill cannot be hid.', about: 'Jesus as Israel’s king. Sermon on the mount, a genealogy, and a commission to the nations.' },
  { id: 'mrk', name: 'Mark', testament: 'New Testament', order: 41, chapters: 16, writer: 'Mark', cite: '10:45', verse: 'The Son of man came not to be ministered unto, but to minister.', about: 'Immediately. A short gospel that runs toward the cross and does not linger on the way.' },
  { id: 'luk', name: 'Luke', testament: 'New Testament', order: 42, chapters: 24, writer: 'Luke', cite: '19:10', verse: 'The Son of man is come to seek and to save that which was lost.', about: 'An orderly account for Theophilus. The poor, the table, and a road to Emmaus.' },
  { id: 'jhn', name: 'John', testament: 'New Testament', order: 43, chapters: 21, writer: 'John', cite: '1:14', verse: 'And the Word was made flesh, and dwelt among us.', about: 'In the beginning was the Word. Signs, I am, and a disciple who writes so you may believe.' },
  { id: 'act', name: 'Acts', testament: 'New Testament', order: 44, chapters: 28, writer: 'Luke', cite: '1:8', verse: 'Ye shall receive power, after that the Holy Ghost is come upon you.', about: 'From Jerusalem to Rome. The church is born, scattered, and still speaking.' },
  { id: 'rom', name: 'Romans', testament: 'New Testament', order: 45, chapters: 16, writer: 'Paul', cite: '1:16', verse: 'I am not ashamed of the gospel of Christ.', about: 'Paul’s longest letter. Jew and Gentile under one mercy, and a life that follows.' },
  { id: '1co', name: '1 Corinthians', testament: 'New Testament', order: 46, chapters: 16, writer: 'Paul', cite: '13:13', verse: 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.', about: 'A gifted, divided church. The cross first, then the body, then love that does not fail.' },
  { id: '2co', name: '2 Corinthians', testament: 'New Testament', order: 47, chapters: 13, writer: 'Paul', cite: '12:9', verse: 'My grace is sufficient for thee: for my strength is made perfect in weakness.', about: 'Paul’s most open letter. Weakness, collection, and a grace that is enough.' },
  { id: 'gal', name: 'Galatians', testament: 'New Testament', order: 48, chapters: 6, writer: 'Paul', cite: '5:1', verse: 'Stand fast therefore in the liberty wherewith Christ hath made us free.', about: 'No other gospel. Freedom is not a license; it is a Spirit that bears fruit.' },
  { id: 'eph', name: 'Ephesians', testament: 'New Testament', order: 49, chapters: 6, writer: 'Paul', cite: '2:8', verse: 'For by grace are ye saved through faith.', about: 'Seated, walking, standing. One new people, and armor for a long night.' },
  { id: 'php', name: 'Philippians', testament: 'New Testament', order: 50, chapters: 4, writer: 'Paul', cite: '4:4', verse: 'Rejoice in the Lord alway: and again I say, Rejoice.', about: 'Joy from a cell. The mind of Christ, and a contentment learned the hard way.' },
  { id: 'col', name: 'Colossians', testament: 'New Testament', order: 51, chapters: 4, writer: 'Paul', cite: '1:17', verse: 'He is before all things, and by him all things consist.', about: 'Christ above every power. Do not be taken by shadows when the body is present.' },
  { id: '1th', name: '1 Thessalonians', testament: 'New Testament', order: 52, chapters: 5, writer: 'Paul', cite: '5:16', verse: 'Rejoice evermore.', about: 'A young church and the coming of the Lord. Work with your hands; wait with hope.' },
  { id: '2th', name: '2 Thessalonians', testament: 'New Testament', order: 53, chapters: 3, writer: 'Paul', cite: '3:13', verse: 'Be not weary in well doing.', about: 'The day has not yet come. Stand, and do not quit the ordinary good.' },
  { id: '1ti', name: '1 Timothy', testament: 'New Testament', order: 54, chapters: 6, writer: 'Paul', cite: '4:12', verse: 'Let no man despise thy youth.', about: 'Charge to a young overseer. Guard the deposit; treat the household as family.' },
  { id: '2ti', name: '2 Timothy', testament: 'New Testament', order: 55, chapters: 4, writer: 'Paul', cite: '4:7', verse: 'I have fought a good fight, I have finished my course, I have kept the faith.', about: 'Paul’s last letter. Come before winter. The word is not bound.' },
  { id: 'tit', name: 'Titus', testament: 'New Testament', order: 56, chapters: 3, writer: 'Paul', cite: '2:11', verse: 'The grace of God that bringeth salvation hath appeared to all men.', about: 'Order on Crete. Grace trains a people to live sensible, just, and godly lives.' },
  { id: 'phm', name: 'Philemon', testament: 'New Testament', order: 57, chapters: 1, writer: 'Paul', cite: '1:16', verse: 'Not now as a servant, but above a servant, a brother beloved.', about: 'One page about a runaway. Receive him as you would receive me.' },
  { id: 'heb', name: 'Hebrews', testament: 'New Testament', order: 58, chapters: 13, writer: 'Unknown', cite: '12:2', verse: 'Looking unto Jesus the author and finisher of our faith.', about: 'Better. A high priest who sat down, and a race that needs endurance.' },
  { id: 'jas', name: 'James', testament: 'New Testament', order: 59, chapters: 5, writer: 'James', cite: '1:22', verse: 'Be ye doers of the word, and not hearers only.', about: 'Faith that works. The tongue, the poor, and wisdom from above.' },
  { id: '1pe', name: '1 Peter', testament: 'New Testament', order: 60, chapters: 5, writer: 'Peter', cite: '2:9', verse: 'Ye are a chosen generation, a royal priesthood.', about: 'Exiles, hope, and a living stone. Suffer as Christians, not as busybodies.' },
  { id: '2pe', name: '2 Peter', testament: 'New Testament', order: 61, chapters: 3, writer: 'Peter', cite: '3:18', verse: 'Grow in grace, and in the knowledge of our Lord.', about: 'Remember. False teachers, a delayed fire, and growth until the day dawns.' },
  { id: '1jn', name: '1 John', testament: 'New Testament', order: 62, chapters: 5, writer: 'John', cite: '4:7', verse: 'Beloved, let us love one another: for love is of God.', about: 'That you may know. Light, love, and a confidence that does not shame us.' },
  { id: '2jn', name: '2 John', testament: 'New Testament', order: 63, chapters: 1, writer: 'John', cite: '1:6', verse: 'This is love, that we walk after his commandments.', about: 'A short word to the elect lady. Walk in truth; do not take the deceiver in.' },
  { id: '3jn', name: '3 John', testament: 'New Testament', order: 64, chapters: 1, writer: 'John', cite: '1:4', verse: 'I have no greater joy than to hear that my children walk in truth.', about: 'Gaius, Diotrephes, Demetrius. Hospitality is how the truth travels.' },
  { id: 'jud', name: 'Jude', testament: 'New Testament', order: 65, chapters: 1, writer: 'Jude', cite: '1:24', verse: 'Now unto him that is able to keep you from falling.', about: 'Contend for the faith. Keep yourselves in the love of God; he is able to keep you.' },
  { id: 'rev', name: 'Revelation', testament: 'New Testament', order: 66, chapters: 22, writer: 'John', cite: '21:5', verse: 'Behold, I make all things new.', about: 'Patmos. Churches, seals, a lamb, and a city where the lamp is the lamb.' },
]

export const featured = books.find((book) => book.id === 'psa') ?? books[0]
export const old = books.filter((book) => book.testament === 'Old Testament')
export const next = books.filter((book) => book.testament === 'New Testament')
